version: 2
jobs:
  build:
    # Test mocknet
    docker:
      - image: qrledger/qrl-docker:xenial
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: apt install -y python3-venv
      - run: pip install -U -r requirements.txt
      - run:
          name: Mocknet Tests
          command: pytest tests/python/mocknet
      - run:
          name: Basic Tests
          command: pytest tests/python/basic

  tests_xenial:
    # Run all tests in xenial
    docker:
      - image: qrledger/qrl-docker:xenial
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: apt install -y python3-venv
      - run: pip install -U -r requirements.txt
      - run:
          name: Mocknet Tests
          command: pytest tests/python/mocknet
      - run:
          name: Basic Tests
          command: pytest tests/python/basic
      - run:
          name: Fork recovery Tests
          command: pytest tests/python/fork_recovery

  tests_bionic:
    # Run all tests in bionic
    docker:
      - image: qrledger/qrl-docker:bionic
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: apt install -y python3-venv
      - run: pip install -U -r requirements.txt
      - run:
          name: Mocknet Tests
          command: pytest tests/python/mocknet
      - run:
          name: Basic Tests
          command: pytest tests/python/basic
      - run:
          name: Fork recovery Tests
          command: pytest tests/python/fork_recovery

  tests_fuzzing:
    # Run all tests in xenial
    docker:
      - image: qrledger/qrl-docker:xenial
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: apt install -y python3-venv
      - run: pip install -U -r requirements.txt
      - run: pip install git+https://github.com/CurataEng/hypothesis-protobuf.git
      - run:
          name: Fuzzing Tests
          command: pytest tests/python/fuzzing

  tests_js:
    # Run javascript tests
    docker:
      - image: qrledger/qrl-docker:xenial
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: apt install -y python3-venv
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: apt-get install -y nodejs
      - run: npm -v
      - run:
          command: ./mocknet/MockNet.py
          background: true
      - run: sleep 15; cd tests/js && npm install && npm rebuild && npm test

  debug:
    # debugging job - this can be customize locally but it wont run in circleci
    # to run this, execute circleci build --job debug
    docker:
      - image: qrledger/qrl-docker:xenial
    environment:
      PYTHONPATH: /root/project
    steps:
      - checkout
      - run: pip install -U -r requirements.txt
      - run: apt install -y python3-venv
      - run:
          name: Debugging -  Adjust accordingly
          command: pytest tests/python/mocknet -k 'test_timeout'


workflows:
  version: 2
  build_all:
    jobs:
      - build
      - tests_xenial
      - tests_bionic
      - tests_js
